apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  ports:
    - port: 4002
  selector:
    app: booking-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: lasindu123/booking-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
            - name: DATABASE_URL
              value: postgresql://securestay:securestay@postgres:5432/securestay
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
