apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - port: 4003
  selector:
    app: payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: lasindu123/payment-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4003
          env:
            - name: PORT
              value: "4003"
            - name: DATABASE_URL
              value: postgresql://securestay:securestay@postgres:5432/securestay
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
