apiVersion: v1
kind: Secret
metadata:
  name: securestay-secrets
type: Opaque
stringData:
  database-url: "postgresql://securestay:securestay@postgres:5432/securestay"
  jwt-secret: "securestay-prod-secret-change-before-deployment"
  rabbitmq-url: "amqp://rabbitmq:5672"
  mongodb-url: "mongodb://mongodb:27017"
  booking-service-internal-url: "http://booking-service:4002"