apiVersion: v1
kind: Secret
metadata:
  name: securestay-secrets
type: Opaque
stringData:
  database-url: "postgresql://securestay:securestay@postgres:5432/securestay"
  jwt-secret: "securestay-minikube-secret"
  rabbitmq-url: "amqp://rabbitmq:5672"
  booking-service-internal-url: "http://booking-service:4002"
