apiVersion: v1
kind: Secret
metadata:
  name: securestay-secrets
type: Opaque
stringData:
  database-url: "postgresql://securestay_admin:<password>@<rds-endpoint>:5432/securestay?sslmode=require"
  jwt-secret: "securestay-prod-secret-change-before-deployment"
  rabbitmq-url: "amqp://securestay_admin:<password>@<rabbitmq-nlb>:5672"
  booking-service-internal-url: "http://booking-service:4002"
  # NOTE: mongodb-url is intentionally removed — notification-service uses database-url (PostgreSQL RDS)
