apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.apiGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
  type: {{ .Values.apiGateway.service.type }}
