apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"
            - name: API_GATEWAY_URL
              value: "http://api-gateway:{{ .Values.apiGateway.port }}"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
