apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: payment-service
  ports:
    - port: {{ .Values.paymentService.port }}
      targetPort: {{ .Values.paymentService.port }}
  type: ClusterIP
